### ISSUE TITLE
7.0如何处理

### ISSUE THREAD

**Issue by jp1017** [GHdeng/NetMonitor#1]
我们知道，安卓7.0谷歌移除了 android.net.conn.CONNECTIVITY_CHANGE 广播，防止一些service 保活等流氓行为，请问该如何处理？可否添加支持7.0

**Comment by GHdeng** [comment]
官方：面向 Android N 开发的应用不会收到 CONNECTIVITY_ACTION 广播，即使它们已有清单条目来请求接受这些事件的通知。 在前台运行的应用如果使用BroadcastReceiver 请求接收通知，则仍可以在主线程中侦听 CONNECTIVITY_CHANGE。
经过测试Android N在主线程监听可用，官方提供JobScheduler API 来处理后台优化。
